### ISSUE TITLE
Updates to mpfr break mpreal.h

### ISSUE THREAD

**Issue by ghborrmann** [advanpix/mpreal#7] opened 2021-05-30 22:00 UTC
Recent patches to Gnu mpfr, as implemented in Fedora's mpfr-devel version 4.1.0-6, cause compilation errors from mpreal.h.  The errors come from mpfr's recently-introduced SRCPTR macro, and occur because mpfr.h and mpreal.h both use the identifier srcptr, with different definitions: it is a pointer in mpfr.h and a function in mpreal.h.  The fix is fairly trivial; it is only necessary to rename mpreal's srcptr function.

**Comment by koder77** [comment] 2021-06-09 19:47
Hello, did you make a patch for mpreal.h? I did notice that the example of mpreal.h can not be compiled anymore. I use mpreal.h for my mpfrc++ math module in my L1VM VM project.

**Comment by ghborrmann** [comment] 2021-06-10 11:28
I merely did a global replace of srcptr() with xsrcptr().  (178 occurrences)

**Comment by srbhp** [comment] 2021-06-14 13:09
May please share your mpreal.h file?

**Comment by koder77** [comment] 2021-06-14 17:50
Hello,

my new "mpreal.h" file is here on my GitHub repo: [GitHub koder77 L1VM](https://github.com/koder77/l1vm/tree/master/vm/modules/mpfr-c%2B%2B)

**Comment by cantonios** [comment] 2021-07-16 19:27
+1

**Comment by MadCatX** [comment] 2021-11-06 11:10
+1

While a fix for this issue is necessary, note that renaming this MPReal function may lead to breakages elsewhere. For instance, Eigen's https://gitlab.com/libeigen/eigen/-/blob/master/unsupported/Eigen/MPRealSupport file needs to be updated to use `mpfr_xsrcptr`.

**Comment by advanpix** [comment] 2022-01-12 15:20
Thanks all for the comments and ideas. Looks like the easiest way would be to define MPFR_USE_NO_MACRO just before including mpfr.h in mpreal.h, e.g.:

```
#define MPFR_USE_NO_MACRO
#include <mpfr.h>
```

This disables all the notorious macro in mpfr.h causing the issue, and also preserves the compatibility with Eigen. 
The only downside is that some utility functions, like isnan, isinf, isfinite, isnum, iszero and isint will become slower to some degree.

What do you think about this simple fix? Or do you prefer the re-naming?

**Comment by MadCatX** [comment] 2022-01-16 20:36
Since Eigen is still actively developed, pushing a patch to Eigen should not be a problem. As such, I'd vote for renaming.

**Comment by advanpix** [comment] 2022-01-17 00:59
As it turns out, there are a lot of software which depend on mpreal.h and its mpfr_srcptr member. Even some of the prominent commercial software packages depend on this, and renaming would be a huge PITA for all the software. I have received quite a few emails about this in the last few days.

So that, at the moment, disabling macro looks like the easiest solution. Speed regression of is** functions can be avoided by static linking to MPFR (so that linker will inline the functions anyway).

**Comment by advanpix** [comment] 2022-01-18 09:32
Fixed by commit 269a03782fa0b87c20470976b88677266c5423ad

**Closed as completed by advanpix** 2022-01-18 09:32 UTC
